import './globals.css'
import { Gabarito } from 'next/font/google'

export const dynamic = 'force-dynamic'

const gabarito = Gabarito({ 
  weight: '500',
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        {children}
      </body>
    </html>
  )
}

